// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Counter from "./Counter.bs.js";

function App(props) {
  return React.createElement(Counter.make, {
              initialValue: 0
            });
}

var make = App;

export {
  make ,
}
/* react Not a pure module */
